[project]
name = "font"
version = "0.1.0"
description = ""
authors = [
    {name = "linlin wang",email = "wanglinlin.cn@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fonttools (>=4.61.0,<5.0.0)",
    "brotli (>=1.2.0,<2.0.0)",
    "zopfli (>=0.4.0,<0.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
